insert into student (name, birthday, groupnumber) values ( 'John','2001-01-01',1 );
insert into student (name, birthday, groupnumber) values ( 'Chris','2001-01-01',1 );
insert into student (name, birthday, groupnumber) values ( 'Carl','2001-01-01',1 );
insert into student (name, birthday, groupnumber) values ( 'Oliver','2001-01-01',2 );
insert into student (name, birthday, groupnumber) values ( 'James','2001-01-01',2 );
insert into student (name, birthday, groupnumber) values ( 'Lucas','2001-01-01',2 );
insert into student (name, birthday, groupnumber) values ( 'Henry','2001-01-01',2 );
insert into student (name, birthday, groupnumber) values ( 'Jacob','2001-01-01',3 );
insert into student (name, birthday, groupnumber) values ( 'Logan','2001-01-01',3 );
insert into student (name, birthday, groupnumber) values ( 'Jaganb','2001-01-01',4 );
insert into student (name, birthday, groupnumber) values ( 'Racob','2001-01-01',5 );
insert into SUBJECT (name, description, grade) VALUES ( 'Art','art_desc',1 );
insert into SUBJECT (name, description, grade) VALUES ( 'Music','music_desc',1 );
insert into SUBJECT (name, description, grade) VALUES ( 'Geography','g_desc',2 );
insert into SUBJECT (name, description, grade) VALUES ( 'History','h_desc',2 );
insert into SUBJECT (name, description, grade) VALUES ( 'PE','pe_desc',3 );
insert into SUBJECT (name, description, grade) VALUES ( 'Math','m_desc',3 );
insert into SUBJECT (name, description, grade) VALUES ( 'Science ','s_desc',4 );
insert into SUBJECT (name, description, grade) VALUES ( 'IT','it_desc',4 );
insert into SUBJECT (name, description, grade) VALUES ( 'SIT','si_desc',5 );
insert into SUBJECT (name, description, grade) VALUES ( 'GIT','gi_desc',5 );
insert into PAYMENTTYPE (name) values ( 'DAILY' );
insert into PAYMENTTYPE (name) values ('WEEKLY');
insert into PAYMENTTYPE (name) values ('MONTHLY');
insert into PAYMENT (type_id, amount, payment_date, student_id) values (2,1.1,NOW(),1);
insert into PAYMENT (type_id, amount, payment_date, student_id) values (3,1.1,NOW(),4);
insert into payment (type_id, amount, payment_date, student_id) values (2, 1.1,NOW(),7);
insert into payment (type_id, amount, payment_date, student_id) values (1, 1.1,NOW(),5);
insert into payment (type_id, amount, payment_date, student_id) values (1, 1.1,NOW(),3);
insert into MARK (student_id, subject_id, mark) VALUES ( 2,1,8 );
insert into MARK (student_id, subject_id, mark) VALUES ( 4,4,5 );
insert into MARK (student_id, subject_id, mark) VALUES ( 5,3,9 );
insert into MARK (student_id, subject_id, mark) VALUES ( 8,6,4 );
insert into MARK (student_id, subject_id, mark) VALUES ( 9,5,9 );
insert into MARK (student_id, subject_id, mark) VALUES ( 3,1,8 );